// Exact headers from the supplied Google Form builder. Never add free-text fields here.
export const FIELDS = {
  "consent": {
    "id": "consent",
    "type": "choice",
    "required": true,
    "title": "Are you happy to take part on the basis described above?",
    "options": [
      "Yes, I agree",
      "No, I do not want to take part"
    ],
    "routes": [
      "profile",
      "SUBMIT"
    ]
  },
  "search_status": {
    "id": "search_status",
    "type": "choice",
    "required": true,
    "title": "Are you currently looking for a job?",
    "options": [
      "Actively applying or interviewing",
      "Looking, but have not started applying",
      "Open to opportunities, but not actively searching",
      "Recently finished my search / accepted an offer",
      "Not currently looking"
    ]
  },
  "employment_status": {
    "id": "employment_status",
    "type": "choice",
    "required": true,
    "title": "Which best describes your current work situation?",
    "options": [
      "Unemployed and looking for work",
      "Employed, have not resigned, and exploring a change",
      "Serving notice and still looking for my next role",
      "Serving notice with my next role already secured",
      "Student / recent graduate seeking my first full-time role",
      "Freelancing / self-employed and seeking an employed role",
      "Returning after a career break",
      "Employed and not looking for a change",
      "Other situation",
      "Prefer not to say"
    ]
  },
  "experience": {
    "id": "experience",
    "type": "choice",
    "required": true,
    "title": "How much total professional work experience do you have?",
    "help": "Include paid internships and freelance work. Do not double-count overlapping roles.",
    "options": [
      "No professional experience yet",
      "Less than 1 year",
      "1 to less than 3 years",
      "3 to less than 5 years",
      "5 to less than 8 years",
      "8 to less than 12 years",
      "12 to less than 16 years",
      "16+ years",
      "Prefer not to say"
    ]
  },
  "target_level": {
    "id": "target_level",
    "type": "choice",
    "required": true,
    "title": "What level of role are you mainly targeting?",
    "options": [
      "Internship / apprenticeship",
      "Entry-level / graduate / junior",
      "Mid-level individual contributor",
      "Senior individual contributor",
      "Lead / staff / principal specialist",
      "Manager / people manager",
      "Head / director",
      "Executive / VP / C-suite",
      "Open to multiple levels",
      "Not currently targeting a role"
    ]
  },
  "function": {
    "id": "function",
    "type": "dropdown",
    "required": true,
    "title": "Which type of work best matches the roles you want?",
    "options": [
      "Software / IT / cybersecurity",
      "AI / machine learning / data / analytics",
      "Engineering / manufacturing / skilled trades",
      "Product / project / program management",
      "Design / creative / media / writing",
      "Sales / business development",
      "Marketing / communications",
      "Finance / accounting / audit",
      "HR / recruitment / people operations",
      "Customer service / operations / administration",
      "Healthcare / care work",
      "Education / research",
      "Legal / public policy",
      "Retail / hospitality / food service",
      "Transport / logistics / supply chain",
      "Other type of work",
      "Still exploring / not applicable"
    ]
  },
  "industry": {
    "id": "industry",
    "type": "dropdown",
    "required": true,
    "title": "Which industry are you mainly applying to?",
    "help": "Choose the employer's industry, rather than your job function. For example, a software role at a bank belongs to financial services.",
    "options": [
      "Technology / software / IT services",
      "Banking / financial services / insurance",
      "Healthcare / pharmaceuticals / biotechnology",
      "Manufacturing / automotive / aerospace",
      "Retail / e-commerce / consumer goods",
      "Education / research",
      "Professional services / consulting",
      "Media / entertainment / advertising",
      "Construction / real estate / infrastructure",
      "Energy / utilities / environment",
      "Transport / logistics",
      "Hospitality / travel / food service",
      "Government / public sector / nonprofit",
      "Agriculture / food production",
      "Multiple industries / no main industry",
      "Other industry",
      "Not currently applying"
    ]
  },
  "age_group": {
    "id": "age_group",
    "type": "choice",
    "required": false,
    "title": "What is your age group? (Optional)",
    "options": [
      "Under 18",
      "18–24",
      "25–34",
      "35–44",
      "45–54",
      "55–64",
      "65+",
      "Prefer not to say"
    ]
  },
  "country": {
    "id": "country",
    "type": "country",
    "required": true,
    "title": "Which country or territory do you currently live in?",
    "options": [
      "Afghanistan",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua & Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia & Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "British Virgin Islands",
      "Brunei",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Caribbean Netherlands",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Congo - Brazzaville",
      "Congo - Kinshasa",
      "Cook Islands",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Curaçao",
      "Cyprus",
      "Czechia",
      "Côte d’Ivoire",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Eswatini",
      "Ethiopia",
      "Falkland Islands",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "France",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guernsey",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard & McDonald Islands",
      "Honduras",
      "Hong Kong SAR China",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Ireland",
      "Isle of Man",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Jersey",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macao SAR China",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia",
      "Moldova",
      "Monaco",
      "Mongolia",
      "Montenegro",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar (Burma)",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfolk Island",
      "North Korea",
      "North Macedonia",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Palestinian Territories",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn Islands",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Romania",
      "Russia",
      "Rwanda",
      "Réunion",
      "Samoa",
      "San Marino",
      "Saudi Arabia",
      "Senegal",
      "Serbia",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Sint Maarten",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia & South Sandwich Islands",
      "South Korea",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "St. Barthélemy",
      "St. Helena",
      "St. Kitts & Nevis",
      "St. Lucia",
      "St. Martin",
      "St. Pierre & Miquelon",
      "St. Vincent & Grenadines",
      "Sudan",
      "Suriname",
      "Svalbard & Jan Mayen",
      "Sweden",
      "Switzerland",
      "Syria",
      "São Tomé & Príncipe",
      "Taiwan",
      "Tajikistan",
      "Tanzania",
      "Thailand",
      "Timor-Leste",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad & Tobago",
      "Tunisia",
      "Turkmenistan",
      "Turks & Caicos Islands",
      "Tuvalu",
      "Türkiye",
      "U.S. Outlying Islands",
      "U.S. Virgin Islands",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City",
      "Venezuela",
      "Vietnam",
      "Wallis & Futuna",
      "Western Sahara",
      "Yemen",
      "Zambia",
      "Zimbabwe",
      "Åland Islands",
      "Other / not listed",
      "Prefer not to say"
    ]
  },
  "target_market": {
    "id": "target_market",
    "type": "choice",
    "required": true,
    "title": "Where are the roles you are targeting mainly based?",
    "options": [
      "In the country where I currently live",
      "In another country",
      "Across several countries / international remote roles",
      "Not sure / not currently targeting roles"
    ]
  },
  "search_duration": {
    "id": "search_duration",
    "type": "choice",
    "required": true,
    "title": "How long have you been looking during your current or most recent job search?",
    "options": [
      "Have not started yet",
      "Less than 1 month",
      "1 to less than 3 months",
      "3 to less than 6 months",
      "6 to less than 12 months",
      "12+ months",
      "Not applicable"
    ]
  },
  "work_arrangement": {
    "id": "work_arrangement",
    "type": "checkbox",
    "required": false,
    "title": "Which work arrangements would you consider? (Select all that apply)",
    "options": [
      "On-site",
      "Hybrid",
      "Fully remote"
    ]
  },
  "recent_activity": {
    "id": "recent_activity",
    "type": "choice",
    "required": true,
    "title": "In the past 30 days, have you applied for a role or taken part in a hiring process?",
    "help": "Include referrals and processes started by a recruiter contacting you.",
    "options": [
      "Yes",
      "No"
    ],
    "routes": [
      "applications",
      "outlook"
    ]
  },
  "channels": {
    "id": "channels",
    "type": "checkbox",
    "required": true,
    "title": "Which channels have you used to apply or enter a hiring process? (Select all that apply)",
    "options": [
      "LinkedIn",
      "Indeed",
      "Naukri",
      "Foundit / Monster",
      "Glassdoor",
      "Wellfound / startup job boards",
      "Other local or industry-specific job boards",
      "Company career websites",
      "Employee referrals / personal network",
      "Recruiters / staffing agencies contacting me",
      "Direct email / direct messages to employers",
      "University / campus placement / career fairs",
      "Government employment services",
      "Other channel"
    ]
  },
  "daily_applications": {
    "id": "daily_applications",
    "type": "choice",
    "required": true,
    "title": "On days when you apply, roughly how many applications do you submit?",
    "help": "Think of a typical application day in the past 30 days. Exclude days when you did not apply; an estimate is fine.",
    "options": [
      "I did not submit applications; I was only interviewing or contacted by recruiters",
      "1–2",
      "3–5",
      "6–10",
      "11–20",
      "21+",
      "It varies too much / not sure"
    ]
  },
  "response_share": {
    "id": "response_share",
    "type": "choice",
    "required": true,
    "title": "For applications submitted 14–30 days ago, about how many have received a decision or next-step response?",
    "help": "Count rejections and invitations to proceed, including automated decisions. Exclude simple 'application received' confirmations. Ignore applications sent less than 14 days ago.",
    "options": [
      "None",
      "Almost none / very few",
      "Fewer than half",
      "About half (roughly 50/50)",
      "More than half",
      "Almost all / all",
      "Not sure",
      "Not applicable — no applications submitted 14–30 days ago"
    ]
  },
  "positive_share": {
    "id": "positive_share",
    "type": "choice",
    "required": true,
    "title": "For those same applications submitted 14–30 days ago, about how many led to an invitation to a next step?",
    "help": "Examples: a recruiter call, assessment, interview or offer. Use all applications in that period as the reference, not only applications that received a reply.",
    "options": [
      "None",
      "Almost none / very few",
      "Fewer than half",
      "About half (roughly 50/50)",
      "More than half",
      "Almost all / all",
      "Not sure",
      "Not applicable — no applications submitted 14–30 days ago"
    ]
  },
  "furthest_stage": {
    "id": "furthest_stage",
    "type": "choice",
    "required": true,
    "title": "What is the furthest hiring stage you reached or completed in the past 30 days?",
    "help": "Include ongoing processes that started earlier. An invitation to interview is different from completing an interview.",
    "options": [
      "Application submitted / acknowledgment only",
      "Recruiter conversation or screening call",
      "Assessment / take-home task completed",
      "Interview completed",
      "Final interview / reference or background checks",
      "Verbal offer only",
      "Written offer received",
      "Offer accepted / started the role",
      "Other stage / not sure"
    ]
  },
  "ghosting_share": {
    "id": "ghosting_share",
    "type": "choice",
    "required": true,
    "title": "In the past 30 days, how often did an employer stop updating you after inviting you to proceed or speaking with you?",
    "help": "Count a process only if an agreed update date passed by at least 7 days, or there was no update for at least 14 days when no date was agreed. Exclude employers who rejected you, explained a delay or whose reply is not yet overdue. Answer across processes with enough time to judge.",
    "options": [
      "Never",
      "Very few of those processes",
      "Fewer than half",
      "About half (roughly 50/50)",
      "More than half",
      "Almost all / all",
      "Not sure",
      "Not applicable — no eligible processes / still waiting within the expected time"
    ]
  },
  "difficulty": {
    "id": "difficulty",
    "type": "choice",
    "required": true,
    "title": "How easy or difficult is it to find openings that match your skills, level and location?",
    "options": [
      "Very easy",
      "Somewhat easy",
      "Neither easy nor difficult",
      "Somewhat difficult",
      "Very difficult",
      "Not sure / have not looked recently"
    ]
  }
};
